function [...
    TX_location_current, ... % VUEs in each rows
    RX_location_current, ... % Column 1: x coordinate, Column 2: y coordinate
    VUE_NS_direction_TX, ... % +1 : moving to north
    VUE_NS_direction_RX, ... % -1 : moving to south
    VUE_EW_direction_TX, ... % +1 : moving to east
    VUE_EW_direction_RX ...  % -1 : moving to west
    ] = Initialize_VUE_Locations( ...
    offset_fixed, ... % TX-RX gap is fixed?
    random_seed ... % control randomness
    )

%% Globals
global offset_distance total_VUE_pairs;

%% manupilate random state
current_random_state = rng;
rng(random_seed);

%% TXs in rows. RXs are east to TXs.
TX_location_current(1:total_VUE_pairs/4,1) = ...
    120*ceil(3*rand(total_VUE_pairs/4,1)-1);
TX_location_current(1:total_VUE_pairs/4,2) = ...
    110*(rand(total_VUE_pairs/4,1));
RX_location_current(1:total_VUE_pairs/4,1) = ...
    TX_location_current(1:total_VUE_pairs/4,1);
RX_location_current(1:total_VUE_pairs/4,2) = ...
    TX_location_current(1:total_VUE_pairs/4,2)+...
    (1-(offset_fixed==0)*(.5)*rand(length(1:total_VUE_pairs/4),1))*offset_distance;

%% TXs in rows. RXs are west to TXs.
TX_location_current(total_VUE_pairs/4+1:total_VUE_pairs/2,1) = ...
    120*ceil(3*rand(total_VUE_pairs/4,1)-1);
TX_location_current(total_VUE_pairs/4+1:total_VUE_pairs/2,2) = ...
    110*(rand(total_VUE_pairs/4,1))+125;
RX_location_current(total_VUE_pairs/4+1:total_VUE_pairs/2,1) = ...
    TX_location_current(total_VUE_pairs/4+1:total_VUE_pairs/2,1);
RX_location_current(total_VUE_pairs/4+1:total_VUE_pairs/2,2) = ...
    TX_location_current(total_VUE_pairs/4+1:total_VUE_pairs/2,2)-...
    (1-(offset_fixed==0)*(.5)*rand(length(total_VUE_pairs/4+1:total_VUE_pairs/2),1))*offset_distance;

%% TXs in columns. RXs are north to TXs.
TX_location_current(total_VUE_pairs/2+1:total_VUE_pairs*3/4,1) = ...
    110*(rand(total_VUE_pairs/4,1));
TX_location_current(total_VUE_pairs/2+1:total_VUE_pairs*3/4,2) = ...
    120*ceil(3*rand(total_VUE_pairs/4,1)-1);
RX_location_current(total_VUE_pairs/2+1:total_VUE_pairs*3/4,1) = ...
    TX_location_current(total_VUE_pairs/2+1:total_VUE_pairs*3/4,1)+...
    (1-(offset_fixed==0)*(.5)*rand(length(total_VUE_pairs/2+1:total_VUE_pairs*3/4),1))*offset_distance;
RX_location_current(total_VUE_pairs/2+1:total_VUE_pairs*3/4,2) = ...
    TX_location_current(total_VUE_pairs/2+1:total_VUE_pairs*3/4,2);

%% TXs in columns. RXs are south of TXs.
TX_location_current(total_VUE_pairs*3/4+1:total_VUE_pairs,1) = ...
    110*(rand(total_VUE_pairs/4,1))+125;
TX_location_current(total_VUE_pairs*3/4+1:total_VUE_pairs,2) = ...
    120*ceil(3*rand(total_VUE_pairs/4,1)-1);
RX_location_current(total_VUE_pairs*3/4+1:total_VUE_pairs,1) = ...
    TX_location_current(total_VUE_pairs*3/4+1:total_VUE_pairs,1)-...
    (1-(offset_fixed==0)*(.5)*rand(length(total_VUE_pairs*3/4+1:total_VUE_pairs),1))*offset_distance;
RX_location_current(total_VUE_pairs*3/4+1:total_VUE_pairs,2) = ...
    TX_location_current(total_VUE_pairs*3/4+1:total_VUE_pairs,2);


VUE_NS_direction_TX = [-1*ones(total_VUE_pairs/4,1);ones(total_VUE_pairs/4,1);...
    zeros(total_VUE_pairs/2,1)]; %%% +1: the north. -1: the south. 0: no
VUE_NS_direction_RX = [-1*ones(total_VUE_pairs/4,1);ones(total_VUE_pairs/4,1);...
    zeros(total_VUE_pairs/2,1)]; %%% +1: the north. -1: the south. 0: no
VUE_EW_direction_TX = [zeros(total_VUE_pairs/2,1);-1*ones(total_VUE_pairs/4,1);...
    ones(total_VUE_pairs/4,1);]; %%% +1: the east.  -1: the south. 0: no
VUE_EW_direction_RX = [zeros(total_VUE_pairs/2,1);-1*ones(total_VUE_pairs/4,1);...
    ones(total_VUE_pairs/4,1);]; %%% +1: the east.  -1: the south. 0: no

%% restore original random state
rng(current_random_state);
end