function Plot_Manhattan( ...
    figure_handler, ...
    TX_location, ....
    RX_location, ...
    VUE_NS_direction_TX, ...
    VUE_NS_direction_RX, ...
    VUE_EW_direction_TX, ...
    VUE_EW_direction_RX, ...
    show_directions ...
    )

figure(figure_handler);
plot(TX_location(:,1),TX_location(:,2),'bo',RX_location(:,1),RX_location(:,2),'rx')
hold on
if (show_directions)
    qHandler = quiver( [TX_location(:,1); RX_location(:,1)], ...
        [TX_location(:,2); RX_location(:,2)], ...
        [VUE_EW_direction_TX; VUE_EW_direction_RX],...
        [VUE_NS_direction_TX; VUE_NS_direction_RX] );
    set(qHandler,'AutoScale','on', 'AutoScaleFactor',0.1);
end
ax = gca;
ax.XLim = ([-5 ,245]);
ax.YLim = ([-5 ,245]);
ax.XTick = ([0: 30: 240]);
ax.YTick = ([0 :30: 240]);
rectangle('Position',[5 5 110 110],'Curvature',0.01);
rectangle('Position',[125 5 110 110],'Curvature',0.01);
rectangle('Position',[5 125 110 110],'Curvature',0.01);
rectangle('Position',[125 125 110 110],'Curvature',0.01);
hold off
tic, pause(0.00001), toc,

end